# Generated by Django 3.2.5 on 2021-08-06 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='dt_altera',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Alteração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='dt_inclui',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Incluisão'),
            preserve_default=False,
        ),
    ]
